#!/bin/csh
##################################################################
# This macro exectutes DISCUS and KUPLOT to create a polygon
# of atoms and its Fourier transform via WWW interface.
#
# Version: 1.0
# Author:  Th. Proffen  (tproffen@lanl.gov)
#          R.B. Neder   (reinhard.neder@mail.uni-wuerzburg.de)
##################################################################
# Required parameters:
#
#    $1,$2 : Propagation u,v
#    $3,$4 : Oscillation x,y
#    $5    : Wavelength
#    $6    : Amplitude
#    $7    : Phase
#    $8    : Radiation to be used
#    $9    : Output graphics size
#
##################################################################
# Here we start DISCUS
##################################################################
#
discus << EOF > /dev/null
set prompt,redirect
set error,exit
fopen 1,teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.err
fput 1,'<h2>An error occured during the calculations.</h2>'
fput 1,'<p>Check that numerical fields contain numbers only'
fput 1,'   and that atom names are spelled correctly'
fclose 1
#
if ($5.le.0.0) then
  fopen 1,teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.err
  fput 1,'<h2>Wavelength needs to be positive !</h2>'
  fclose 1
else
  sys echo 'title Structure in Spacegroup P1      '  > $$.cll
  sys echo 'spcgr P1                              ' >> $$.cll
  sys echo 'cell 5.00 5.00 5.00 90. 90. 90.       ' >> $$.cll
  sys echo 'atoms                                 ' >> $$.cll
  sys echo 'PB   0.00  0.00  0.00   0.4           ' >> $$.cll
#
  read
  cell $$.cll,40,40,1
#
  r[99]=sqrt($1**2+$2**2)
  r[10]=1.0/(nint(100.0*r[99]/$5)/100.0/r[99])
#
  wave
    func sinus
    acco
    trans
    len r[10]
    vec $1,$2,0.0
    osc $3,$4,0.0
    ampl $6
    phase 90.0+$7
    sel pb
    run
  exit
#
  plot
    sel all
    ext all
    set PB,3,3,0.7
    uvw 0,0,1
    thick 1.0
    outfile $$.plot
    run
  exit
#
  if ($8.eq.1) then
    four
    xray
    exit
  else
    four
    neut
    exit
  endif
#
  four
    ll -0.5,-0.5,0.0
    lr  3.5,-0.5,0.0
    ul -0.5, 3.5,0.0
    no 81
    na 81
    run
  exit
#
  output
    value inte
    form stand
    outf $$.inte
    run
  exit
#
  system rm -f teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.err
#
endif
exit
EOF
#
##################################################################
# Here we start KUPLOT
##################################################################
#
if (-f teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.err) then
  rm -f $$.*
  exit 1
endif
#
kuplot << EOF > /dev/null
set prompt,redirect
set error,exit
fopen 1,teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.err
fput 1,'<h2>An error occured during the calculations.</h2>'
fput 1,'<p>Check that numerical fields contain numbers only'
fput 1,'   and that atom names are spelled correctly'
fclose 1
#
rese
#
load cr,$$.plot
load ni,$$.inte
#
buf 0.06
lwid 0,0.1
font just,center
font typ,1,1
font typ,2,1
font typ,3,1
font typ,4,1
font typ,5,1
font typ,6,1
#
nfra 4
sfra 1,0.0,0.3,0.5,1.0
sfra 2,0.5,0.3,1.0,1.0
sfra 3,0.0,0.0,0.4,0.3
sfra 4,0.4,0.0,1.0,0.3
#
afra 1
kfra 1,1
ccal add,wx,1,11.0
ccal add,wy,1,11.0
fset 2
mark 5,5
grid on
aver 1
skal 0.,20.,0.,20.
achx x [l.u.]
achy y [l.u.]
tit2 Modulated structure
fnam off
#
afra 2
kfra 2,2
skal
mark 1,1
aver 1
achx h
achy k
achz Intensity
if ($8.eq.1) then
  tit1 Scattering: X-ray
else
  tit1 Scattering: Neutrons
endif
tit2 Scale: 10% strongest Bragg peak
fnam off
grid off
fset 2
hlin 1,0.0,10.0,1,%
hart 2,2
cmap fire
cmap invert
#
fopen 1,$$.txa
fput 1,' '
fput 1,'    Propagation direction [l.u.] : '
fput 1,'    Oscillation direction [l.u.] : '
fput 1,'    Wavelength [\A] : '
fput 1,'    Amplitude [\A] : '
fput 1,'    Phase \gf [degrees] : '
fclose 1
#
fopen 1,$$.txb
fput 1,' '
fput 1,$1,$2,0.0
fput 1,$3,$4,0.0
fput 1,$5,'  => ',$5/5.0,' unit cells'
fput 1,$6
fput 1,$7
fclose 1
#
afra 3
kfra 3,$$.txa
font color,5,6
font size,5,14
font just,left
#
afra 4
kfra 4,$$.txb
font color,5,3
font size,5,14
font just,left
#
save ps,teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.ps
size[3]=$9
save pic,teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.gif
#
system rm -f teach_dwave_$1_$2_$3_$4_$5_$6_$7_$8_$9.err
#
exit
EOF
#
##################################################################
# Some cleaning up - only GIF output remains
##################################################################
#
rm -f $$.*
