################################################################################
# Nano particle builder. Please read this header for information about
# macro conventions to be used for the web interface. 
#
# (1) Filenames
# -------------
# The CGI script is called with the directory name as parameter. Each
# builder needs to live in its own directory and the main macro *must*
# be called 'main.mac'. This is the only macro that needs to have some
# specific information in the header to allow building of the input
# form (see next section).
#
# Output files need to be saved in the directory/name passed as (N+1)th. 
# parameter. The following extensions are used 
#
# .pow  - Powder diffraction pattern
# .gr   - Calculated PDF
# .nipl - Calculated diffuse scattering plane 
# .cif  - CIF file of resulting structure 
# .info - Any text output (HTML) which will be included on output page.
#
# (2) main.mac header information
# -------------------------------
#
# The CGI script will build a HTML form based on the lines given in the
# header of this macro. Every parameter $1, $2, .. used in main.mac
# The line needs to start with ##Parameter and be followed by the 
# parameter number (corresponding to the $1, $2 used in the macro), type,
# label and optional parameters depending on the type. All values are
# separated by ','.
#
# Parameter <number>,"real",<label>,<min-allowed>,<max-allowed>
# Parameter <number>,"integer",<label>,<min-allowed>,<max-allowed>
# Parameter <number>,"file",<label>,<mask for file selection>
# Parameter <number>,"select",<label1:label2:..>,<value1:value2:..>
#
# (3) Other
# ---------
#
# - The macro needs to end with the command 'exit' !!!
# - default.mac call main.mac with the default settings used when the 
#   builder is initially called.
#
################################################################################
# SPECIFIC to this builder
################################################################################
#
## Parameter 1,real,Radius in ab (A),10,50
## Parameter 2,real,Radius in c (A),20,50
## Parameter 3,file,Structure,cells/nano_*.cell
## Space
## Parameter 4,select,Radiation,X-ray:Neutron,xray:neut
## Parameter 5,select,Calculate,None:Powder:PDF:Both,0:1:2:3
#
################################################################################
#
## Usage: @main size_ab,size_c,cell_file,radiation,cflag,output_root
#
variable real,    radius_ab
variable real,    radius_c
variable real,    radius
variable integer, ncell_ab
variable integer, ncell_c
variable real,    rhozero
#
read
  cell $3
#
rhozero = n[1]/vol[1]
#
radius_ab = $1
radius_c  = $2
radius    = max(radius_ab,radius_c)
ncell_ab  = 2*(nint(radius_ab/lat[1])+1)
ncell_c   = 2*(nint(radius_c /lat[3])+1)
#
read
  cell $3,ncell_ab,ncell_ab,ncell_c
#
@shear    radius_ab, radius_c
boundary  sphere   , radius_ab
@shear    radius_c , radius_ab
#
purge
#
if ($5.eq.1 .or. $5.eq.3) then
  @powder $4,$6
endif
if ($5.eq.2 .or. $5.eq.3) then
  @pdf    $4,$6
endif
#
@plotx  $6
#
fopen 1,$6.info
fput 1,"<b>Number of atoms</b>: %d",n[1]
fclose 1
#
exit
#
